modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
modUrl = "${modrinth}"
logoFile = "${mod_id}.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''
updateJSONURL = "${update_lookup}"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "loot_journal.neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "fragmentum"
type = "required"
versionRange = "[${fragmentum_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[${yacl_version},)"
ordering = "NONE"
side = "BOTH"